name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Set Git Identity
        run: |
          git config --global user.name "Hardik"
          git config --global user.email "hardikanand47h@gmail.com"

      - name: Pull from Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git pull --rebase https://hardik1247:$HF_TOKEN@huggingface.co/spaces/hardik1247/Search_Engine_llm main

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --verbose https://hardik1247:$HF_TOKEN@huggingface.co/spaces/hardik1247/Search_Engine_llm main
